remote_theme: "mmistakes/minimal-mistakes@4.20.2"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
repository: "wikitables/web-of-data-tables"
plugins:
  - jekyll-include-cache
